# This file contains values from Cookiecutter

default_context:
  project_name: "pyGascard"
  project_description: "Python API for acquisition and control of Edinburgh Sensors Gascard"
  organization: "ulfsri"
  license: "MIT"
  minimal_python_version: 3.9
  github_name: "pyGascard"
  email: "grayson.bellamy@ul.org"
  version: "0.1.0"
  line_length: "88"
  create_example_template: "none"
